services:
  server:
    container_name: fume-fhir-converter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "42420:42420"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        compress: "true"
    env_file:
      - ./.env
